### ISSUE TITLE
Upgrade to latest API version

### ISSUE THREAD

**Issue by KeshiaRose** [hutchijo/my_tableau_extensions#1]
Hi Joel,

I just noticed your extension that you submitted to our community page a while back never got added. I would love to add it now, but would you be able to update it to the latest version of the API? (https://github.com/tableau/extensions-api/blob/master/lib/tableau-extensions-1.latest.js)

Take care,
Keshia

**Comment by hutchijo** [comment]
Hi Keshia,

I just updated my project to use the latest extension API code.  Thank you
for considering this for the community page.

-Joel

**Comment by KeshiaRose** [comment]
Awesome! Added it to the community page! Thanks!
